#!/usr/bin/env ruby
if `git log -1 --format=format:%H`.chars.each_slice(20).map{ |part| part.inject(0){ |sum, ch| sum + ch.hex } }.uniq.count == 1
  puts '**************************************'
  puts '*   Congratulations! Lucky commit!   *'
  puts '**************************************'
end
