#!/usr/bin/env ruby

puts "installing language specs"
puts `cp -v gedit/*.lang /usr/share/gtksourceview-2.0/language-specs/`
puts "installing styles"
puts `cp -v gedit/*.xml /usr/share/gtksourceview-2.0/styles/`
